// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDeB9jAlnVsuhKL2jXbjqy6-axKcD90QE4',
    appId: '1:170740419984:web:446ab34a5b3348f3a1b715',
    messagingSenderId: '170740419984',
    projectId: 'latest-student',
    authDomain: 'latest-student.firebaseapp.com',
    storageBucket: 'latest-student.firebasestorage.app',
    measurementId: 'G-2JCLZCXSWT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCPANAAUWEdARLMEkSZA7GfwxI_qnDS4Cg',
    appId: '1:170740419984:android:7425ef9b996c654ba1b715',
    messagingSenderId: '170740419984',
    projectId: 'latest-student',
    storageBucket: 'latest-student.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCAoVpneig94UIVAEJri4VGpe7-P6yv-gY',
    appId: '1:170740419984:ios:1c208808f02423eca1b715',
    messagingSenderId: '170740419984',
    projectId: 'latest-student',
    storageBucket: 'latest-student.firebasestorage.app',
    iosBundleId: 'com.example.studentApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCAoVpneig94UIVAEJri4VGpe7-P6yv-gY',
    appId: '1:170740419984:ios:1c208808f02423eca1b715',
    messagingSenderId: '170740419984',
    projectId: 'latest-student',
    storageBucket: 'latest-student.firebasestorage.app',
    iosBundleId: 'com.example.studentApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDeB9jAlnVsuhKL2jXbjqy6-axKcD90QE4',
    appId: '1:170740419984:web:c6427f5eef813c8da1b715',
    messagingSenderId: '170740419984',
    projectId: 'latest-student',
    authDomain: 'latest-student.firebaseapp.com',
    storageBucket: 'latest-student.firebasestorage.app',
    measurementId: 'G-D0KQJ3JB7N',
  );

}